# Generated by Django 2.1.5 on 2019-01-29 13:14

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='tarea',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100)),
                ('fecha_creado', models.DateField()),
                ('fecha_venc', models.DateField()),
                ('coment', models.CharField(max_length=300)),
                ('priori', models.CharField(max_length=20)),
            ],
        ),
    ]
