# Generated by Django 2.1.5 on 2019-01-29 15:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tareas', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='tarea',
            name='resuelta',
            field=models.BooleanField(default=False),
        ),
    ]
